server.port=8080

spring.application.name=insight-vault

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

spring.ai.model.chat=openai
spring.ai.model.embedding=transformers
spring.ai.openai.api-key=${openai.api-key}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.com.ai.applications.rag.insightvault=DEBUG

app.storage.root-location=./data/uploads
app.storage.max-file-size-bytes=20971520
app.bootstrap.admin-username=admin
app.bootstrap.admin-password=admin123
app.bootstrap.user-username=user
app.bootstrap.user-password=user123
